name: Human Capital Focus
favicon: null
layout_spectrum: 0.76339
typography_spectrum: 0.27240768214687705
title: 'Human Capital Focus, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9d600'
    - '#7f9e12'
    - '#0288dd'
    - '#003d1e'
  brandStrength: 0.5134313886519521
  lightness: 0.17699998803436756
  saturation: 0.21135120769031346
  rhythmicContrast: 0.679956701816991
purpose: []
